# 서버 관련 기본 설정
server:
  port: 80  # 서버가 실행될 포트 번호
  servlet:
    encoding:
      charset: UTF-8  # 문자 인코딩을 UTF-8로 설정
      force: true    # 모든 요청/응답에 강제로 인코딩 적용

  tomcat:
    max-swallow-size: 50MB      # Tomcat의 최대 스왈로우 크기
    max-http-form-post-size: 50MB  # Tomcat의 최대 POST 요청 크기

# Spring 프레임워크 관련 설정
spring:
  # 데이터베이스 연결 설정
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy  # SQL 로깅을 위한 JDBC 드라이버
    url: ENC(o6oqvMIjx+qqudp/OxFhqUTWGcGlI0qkVaEMkaMgzPmSBMbbN9xnbJiRk1ey4EMROA9nwmW9MndJzu3Y2VfIg2ofBo4nlzPgOS0yZ29tlnbeX3mcvIh7PQ==)
    username: ENC(a0E+w5V96368ZbbGuQA1Kg==)
    password: ENC(pj2nIfjYWFQnQmWpcwEgx3+G834oNjX5bXl3cVDSzCg=)

  # JPA(Java Persistence API) 설정
  jpa:
    hibernate:
      ddl-auto: update  # 데이터베이스 스키마 자동 업데이트
    show-sql: true      # SQL 쿼리 로깅 활성화
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리 포맷팅
    database-platform: org.hibernate.dialect.MySQLDialect  # MySQL 데이터베이스 방언 설정

  # 정적 리소스 설정
  web:
    resources:
      static-locations: classpath:/static/  # 정적 파일 위치
      add-mappings: true                    # 정적 리소스 매핑 활성화
      chain:
        strategy:
          content:
            enabled: true                    # 리소스 체인 전략 활성화
            paths: /**                       # 모든 경로에 적용
      cache:
        period: 0                           # 캐시 비활성화

  servlet:
    multipart:
      max-file-size: 50MB        # 단일 파일의 최대 크기
      max-request-size: 50MB     # 전체 요청의 최대 크기
      file-size-threshold: 0     # 파일이 메모리에 저장되는 임계값
      enabled: true              # multipart 업로드 활성화

  # MVC 패턴 매칭 전략 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher   # URL 경로 매칭 전략 설정

  # Google Cloud Storage 설정
  cloud:
    gcp:
      storage:
        credentials:
          location: ${GOOGLE_APPLICATION_CREDENTIALS}  # GCP 인증 정보 위치
        project-id: ENC(E8keV70I9+OaNeMrARacJPx0uMzPvcOgm/6hgWcOlWk=)
        bucket: smart_office  # GCS 버킷 이름

  # Redis 설정
  data:
    redis:
      host: ${SERVER_URL}        # Redis 서버 호스트
      port: 6379                 # Redis 포트
      password: ${REDIS_PASSWORD}  # Redis 비밀번호

# 로깅 기본 설정 (상세 설정은 logback.xml에서 관리)
logging:
  config: classpath:logback.xml   # logback 설정 파일 위치
  level:
    root: info  # 기본 로그 레벨 (logback.xml의 root level과 동일하게 설정)
  charset:
    console: UTF-8

# Swagger/OpenAPI 문서화 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html           # Swagger UI 경로
    enabled: true                    # Swagger UI 활성화
    disable-swagger-default-url: true
    url: /v3/api-docs               # OpenAPI 문서 URL
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: Smart Office API       # API 문서 이름

  api-docs:
    path: /v3/api-docs              # OpenAPI 문서 경로
  default-consumes-media-type: application/json  # 기본 요청 미디어 타입
  default-produces-media-type: application/json  # 기본 응답 미디어 타입

# application.yml
file:
  max-size: 52428800  # 50MB
  allowed-types: >
    image/jpeg,
    image/png,
    image/gif,
    application/pdf,
    application/msword,
    application/vnd.openxmlformats-officedocument.wordprocessingml.document,
    application/vnd.ms-excel,
    application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,
    application/vnd.ms-powerpoint,
    application/vnd.openxmlformats-officedocument.presentationml.presentation,
    text/plain,
    application/zip,
    application/x-zip-compressed,
    application/x-rar-compressed,
    application/haansofthwp


fast-api:
  api:
    base-url: ${FAST_API_SERVER_URL}